In [2]:
import mlflow
mlflow.set_experiment("mlops-learn")
mlflow.autolog()

2026/02/26 00:47:28 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2026/02/26 00:47:28 INFO mlflow.store.db.utils: Updating database tables
2026/02/26 00:47:49 INFO mlflow.tracking.fluent: Experiment with name 'mlops-learn' does not exist. Creating a new experiment.

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
!ls data/

matchStats.csv	playerStats.csv  teamStats.csv

In [ ]:
matchStats = pd.read_csv("data/matchStats.csv")
playerStats = pd.read_csv("data/playerStats.csv")
teamStats = pd.read_csv("data/teamStats.csv")

,Rank,Team,Total,Won,Lost,3-0,3-1,3-2,2-3,1-3,0-3,Points,Sets Won,Sets Lost,Set Ratio,Points Won,Points Lost,Point Ratio
0,1,Brazil,12,11,1,5,4,2,1,0,0,32,35,11,3.181,1095,998,1.097
1,2,Italy,12,10,2,5,2,3,1,1,0,28,33,14,2.357,1100,962,1.143
2,3,France,12,8,4,4,2,2,2,2,0,24,30,18,1.666,1124,1050,1.070
3,4,Japan,12,8,4,5,1,2,1,1,2,23,27,17,1.588,1036,977,1.060
4,5,Poland,12,8,4,3,2,3,2,2,0,23,30,20,1.500,1157,1129,1.024

In [8]:
matchStats.head()

,Date,Home Team,Away Team,Winner,Loser,Kills Home,Kills Away,Blocks Home,Blocks Away,Aces Home,...,Set1 Home,Set1 Away,Set2 Home,Set2 Away,Set3 Home,Set3 Away,Set4 Home,Set4 Away,Set5 Home,Set5 Away
0,2025-08-02,Italy,Slovenia,Italy,Slovenia,62,52,10,9,9,...,25,22,22,25,25,21,25.0,18.0,NaN,NaN
1,2025-08-02,Brazil,Poland,Poland,Brazil,32,41,7,6,6,...,26,28,19,25,21,25,NaN,NaN,NaN,NaN
2,2025-08-03,Brazil,Slovenia,Brazil,Slovenia,48,49,11,7,5,...,23,25,25,20,25,23,25.0,19.0,NaN,NaN
3,2025-08-03,Poland,Italy,Poland,Italy,37,27,10,6,3,...,25,22,25,19,25,14,NaN,NaN,NaN,NaN
4,2025-07-30,Italy,Cuba,Italy,Cuba,42,55,9,6,7,...,25,18,25,19,20,25,25.0,21.0,NaN,NaN

In [9]:
playerStats.head()

,Player Name,Team,Position,Age,Height,Running Sets,Setting Errors,Still Sets,Sets Per Match,Successful Receives,...,Rebounds,Blocks Per Match,Great Saves,Defensive Errors,Defensive Receptions,Digs Per Match,Kills,Attacking Errors,Attacking Attempts,Attacks Per Match
0,A. Lagumdzija,TUR,OPPOSITE SPIKER,26,211cm,1,0,4,0.25,1,...,11,1.00,25,14,5,6.25,60,18,65,15.00
1,A. Nikolov,BUL,OUTSIDE HITTER,21,207cm,6,1,36,0.50,46,...,22,1.25,61,17,31,5.08,177,54,124,14.75
2,Adamczyk,POL,MIDDLE BLOCKER,26,208cm,0,0,3,0.00,0,...,4,0.75,2,4,4,0.50,11,1,8,2.75
3,Adriano,BRA,OUTSIDE HITTER,23,201cm,0,0,9,0.00,9,...,5,0.07,9,6,4,0.60,12,10,21,0.80
4,Ahyi,NED,OPPOSITE SPIKER,27,200cm,2,0,22,0.17,0,...,22,1.17,33,36,29,2.75,161,53,115,13.42

In [10]:
teamStats.head()

,Rank,Team,Total,Won,Lost,3-0,3-1,3-2,2-3,1-3,0-3,Points,Sets Won,Sets Lost,Set Ratio,Points Won,Points Lost,Point Ratio
0,1,Brazil,12,11,1,5,4,2,1,0,0,32,35,11,3.181,1095,998,1.097
1,2,Italy,12,10,2,5,2,3,1,1,0,28,33,14,2.357,1100,962,1.143
2,3,France,12,8,4,4,2,2,2,2,0,24,30,18,1.666,1124,1050,1.070
3,4,Japan,12,8,4,5,1,2,1,1,2,23,27,17,1.588,1036,977,1.060
4,5,Poland,12,8,4,3,2,3,2,2,0,23,30,20,1.500,1157,1129,1.024